create_clock -period 15.00 -name clk_i -waveform {0.000 7.500} [get_ports clk_i]
set_input_delay -clock [get_clocks clk_i] -min -add_delay 0.000 [get_ports {sw_i[*]}]
set_input_delay -clock [get_clocks clk_i] -max -add_delay 4.000 [get_ports {sw_i[*]}]
set_input_delay -clock [get_clocks clk_i] -min -add_delay 0.000 [get_ports rst_ni]
set_input_delay -clock [get_clocks clk_i] -max -add_delay 4.000 [get_ports rst_ni]
set_input_delay -clock [get_clocks clk_i] -min -add_delay 0.000 [get_ports start_i]
set_input_delay -clock [get_clocks clk_i] -max -add_delay 4.000 [get_ports start_i]
set_input_delay -clock [get_clocks clk_i] -min -add_delay 0.000 [get_ports write_i]
set_input_delay -clock [get_clocks clk_i] -max -add_delay 4.000 [get_ports write_i]
set_output_delay -clock [get_clocks clk_i] -min -add_delay 0.000 [get_ports {led_o[*]}]
set_output_delay -clock [get_clocks clk_i] -max -add_delay 2.000 [get_ports {led_o[*]}]
set_false_path -from [get_ports rst_ni]
set_false_path -from [get_ports {start_i write_i sw_i[*]}]
